### ISSUE TITLE
Uncaught Error: Notification must be created with string message: undefined

### ISSUE THREAD

**Issue by lit-af** [aklos/save-notification#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [save-notification](https://github.com/aklos/save-notification) package, v0.9.0
### Stack Trace

Uncaught Error: Notification must be created with string message: undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:25

Error: Notification must be created with string message: undefined
    at Notification.module.exports.Notification.validate (/Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:25:15)
    at new Notification (/Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:20:12)
    at NotificationManager.module.exports.NotificationManager.addInfo (/Applications/Atom.app/Contents/Resources/app.asar/src/notification-manager.js:33:35)
    at Object.module.exports.SaveNotification.notify (/Users/Alexandre/.atom/packages/save-notification/lib/save-notification.coffee:43:41)
    at atom-workspace.subscriptions.add.atom.commands.add.core:save (/Users/Alexandre/.atom/packages/save-notification/lib/save-notification.coffee:26:77)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:04.2.0 application:new-file (atom-pane.pane.active)
     -0:02.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:00.8.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
language-gherkin-i18n, v1.3.4
save-notification, v0.9.0

# Dev
No dev packages
```

**Comment by aklos** [comment]
Added check for filePath before attempting info notification.
